"""Live end-to-end memory tests over a real GraphRAG benchmark corpus.

Drives all three memory tiers — short-term (session working context), episodic
(the durable append-only log), and long-term (curated cross-session records) —
against the first novel corpus of the GraphRAG-Benchmark, ``Novel-30752``
("Vestiges of the Mayas"), and the 87 benchmark questions written for it.

The corpus text and questions are checked in as fixtures under ``tests/test_data/``
(regenerated by ``_regen_fixtures`` at the bottom of this file from
``ref_projects/GraphRAG-Benchmark/Datasets/``).

Nothing is faked: the LLM and embedder come from ``.env.yaml`` (see
``tests/live_setup``) and every store is a real persistent backend —
``SQLiteStructuredStore`` (a sqlite file), ``FAISSVectorStore`` (file-backed
FAISS), ``LocalFSLogStore`` and ``LocalFSDocumentStore`` (on-disk). The novel is
chunked, embedded, and upserted into FAISS so the query runner answers real
questions through ``vector_search``; the memory tiers ride on top.

Run with::

    pytest tests/memory/test_novel_memory_live.py -m live
"""

from __future__ import annotations

import asyncio
import json
import logging
import math
from pathlib import Path

import pytest
import yaml

from cogbase.core.models import Document
from cogbase.core.query_runner import MemoryTiers, QueryResult, QueryRunner, RetrievalResources
from cogbase.memory import (
    Distiller,
    EpisodicMemory,
    LongTermMemory,
    ReviewDecision,
    ShortTermMemory,
)
from cogbase.memory.long_term import MAX_REVIEW_BATCH
from cogbase.memory.models import MemoryCandidate, MemoryKind, MemoryStatus
from cogbase.pipeline.chunking.langchain import build_recursive_chunker
from cogbase.stores.document.local_fs import LocalFSDocumentStore
from cogbase.stores.filters import Col
from cogbase.stores.log.local_fs import LocalFSLogStore
from cogbase.stores.scope import AppScope
from cogbase.stores.structured.sqlite import SQLiteStructuredStore
from cogbase.stores.vector.base import VectorCollectionSchema
from cogbase.stores.vector.faiss_store import FAISSVectorStore
from tests.live_setup import make_llm, make_embedding

logger = logging.getLogger(__name__)

_llm = make_llm()
_embedder = make_embedding()

pytest.importorskip("faiss", reason="faiss not installed")

pytestmark = [
    pytest.mark.live,
    pytest.mark.skipif(
        _llm is None or _embedder is None,
        reason="No LLM/embedder configured: set llm+embedding in .env.yaml or OPENAI_API_KEY",
    ),
]

_DATA_DIR = Path(__file__).resolve().parent.parent / "test_data"
_CORPUS_FILE = _DATA_DIR / "novel_30752_corpus.txt"
_QUESTIONS_FILE = _DATA_DIR / "novel_30752_questions.json"

# Reuse the GraphRAG benchmark's query prompt so the runner answers in the same
# concise, evidence-grounded style the benchmark grades against.
_BENCH_APP_FILE = (
    Path(__file__).resolve().parents[2]
    / "benchmarks" / "graphrag" / "bench_app_simple.yaml"
)
_QUERY_PROMPT = yaml.safe_load(_BENCH_APP_FILE.read_text(encoding="utf-8"))["query_prompt"]

_APP_ID = "novel-30752"
_PASSAGES = "novel_passages"


def _load_questions() -> list[dict]:
    return json.loads(_QUESTIONS_FILE.read_text(encoding="utf-8"))


def _find_question(questions: list[dict], needle: str) -> dict:
    """Return the benchmark question whose text contains *needle* (case-insensitive)."""
    needle = needle.lower()
    for q in questions:
        if needle in q["question"].lower():
            return q
    raise AssertionError(f"no benchmark question contains {needle!r}")


class _NovelEnv:
    """Bundle of the persistent stores + memory tiers for one test session."""

    def __init__(self, *, vector, structured, log, docs, episodic, short_term,
                 long_term, vector_schema):
        self.vector = vector
        self.structured = structured
        self.log = log
        self.docs = docs
        self.episodic = episodic
        self.short_term = short_term
        self.long_term = long_term
        self.vector_schema = vector_schema

    def runner(self, *, with_long_term=False, long_term=None) -> QueryRunner:
        """Build a runner over the ingested corpus.

        ``with_long_term`` wires this env's own long-term store; ``long_term``
        overrides it with any other store (used to compare freshly-distilled
        memory stores against the no-memory baseline).
        """
        lt = long_term if long_term is not None else (self.long_term if with_long_term else None)
        return QueryRunner(
            app_id=_APP_ID,
            llm=_llm,
            resources=RetrievalResources(
                document_store=self.docs,
                vector_store=self.vector,
                embedder=_embedder,
                vector_schemas=[self.vector_schema],
            ),
            memory=MemoryTiers(
                short_term=self.short_term,
                episodic=self.episodic,
                long_term=lt,
            ),
        )


async def _build_and_ingest(persist: Path) -> _NovelEnv:
    """Build every persistent store and ingest the novel into FAISS (once)."""
    corpus = _CORPUS_FILE.read_text(encoding="utf-8")

    vector = FAISSVectorStore(path=persist / "novel_faiss")
    structured = SQLiteStructuredStore(persist / "novel.sqlite")
    log = LocalFSLogStore(persist / "logs")
    docs = LocalFSDocumentStore(persist / "docs")

    episodic = EpisodicMemory(log)
    short_term = ShortTermMemory(episodic=episodic, llm=_llm)

    # Long-term rides on its own app-scoped persistent stores (sqlite + faiss).
    long_term = LongTermMemory(
        SQLiteStructuredStore(persist / "long_term.sqlite").with_scope(AppScope(app_id=_APP_ID)),
        FAISSVectorStore(path=persist / "long_term_faiss").with_scope(AppScope(app_id=_APP_ID)),
        _llm,
        _embedder,
        app_id=_APP_ID,
    )

    # Chunk → embed → upsert the novel into a real FAISS collection.
    chunks = build_recursive_chunker(chunk_size=1024, overlap=128).chunk(
        Document(doc_id="Novel-30752", text=corpus)
    )
    embeddings = await _embedder.embed([c.text for c in chunks])
    dims = len(embeddings[0])

    vector_schema = VectorCollectionSchema(
        name=_PASSAGES,
        dimensions=dims,
        description="Passages from the novel 'Vestiges of the Mayas' (Novel-30752).",
    )
    env = _NovelEnv(
        vector=vector, structured=structured, log=log, docs=docs,
        episodic=episodic, short_term=short_term, long_term=long_term,
        vector_schema=vector_schema,
    )
    await vector.create_collection(env.vector_schema)
    await vector.upsert(
        _PASSAGES,
        [c.model_copy(update={"embedding": e}) for c, e in zip(chunks, embeddings)],
    )
    logger.info("[novel] ingested %d passages, dims=%d", len(chunks), dims)
    return env


@pytest.fixture(scope="module")
def env(tmp_path_factory) -> _NovelEnv:
    """Module-scoped: build the stores and ingest the corpus once.

    Built on a throwaway loop (the stores are loop-agnostic — sqlite is sync,
    FAISS/localfs use ``get_event_loop`` at call time), then reused by each
    function-scoped async test.
    """
    persist = tmp_path_factory.mktemp("novel_memory")
    return asyncio.run(_build_and_ingest(persist))


async def _query_result(runner: QueryRunner, text: str, *, session_id: str | None = None) -> QueryResult:
    result: QueryResult | None = None
    async for item in runner.run(text, base_prompt=_QUERY_PROMPT, session_id=session_id):
        if isinstance(item, QueryResult):
            result = item
    assert result is not None, f"runner produced no QueryResult for {text!r}"
    return result


async def _query(runner: QueryRunner, text: str, *, session_id: str | None = None) -> str:
    return (await _query_result(runner, text, session_id=session_id)).answer


# ---------------------------------------------------------------------------
# Short-term (session) + episodic, driven by real benchmark questions.
# ---------------------------------------------------------------------------


class TestShortTermAndEpisodicLive:
    async def test_multiturn_session_carries_context_and_persists_log(self, env):
        questions = _load_questions()
        # A fact-retrieval question whose answer ("Uxmal") is a distinctive token.
        q1 = _find_question(questions, "noted for its maya inscriptions")
        assert "uxmal" in q1["answer"].lower()

        sid = await env.short_term.start_session(app_id=_APP_ID)

        # Turn 1 — answered through real vector_search over the novel.
        answer1 = (await _query(env.runner(), q1["question"], session_id=sid)).lower()
        assert "uxmal" in answer1, f"expected Uxmal in turn-1 answer:\n{answer1}"

        # Turn 2 — a bare follow-up that only resolves via short-term context.
        # "that same site" refers to Uxmal from turn 1; the Dwarf's House mystery
        # is at Uxmal in the corpus. No caller history is passed: short-term must
        # rehydrate the prior turn from the episodic log.
        answer2 = (
            await _query(
                env.runner(),
                "At that same site, what legendary building is tied to mysteries there?",
                session_id=sid,
            )
        ).lower()
        assert "dwarf" in answer2, (
            "expected the Dwarf's House (Uxmal) — turn 2 needs short-term context "
            f"to resolve 'that same site':\n{answer2}"
        )

        # Short-term projection: both turns are present in the rehydrated thread.
        state = await env.short_term.get(sid)
        assert state is not None
        contents = " ".join(m.content for m in state.messages).lower()
        assert "maya inscriptions" in contents  # turn-1 user message
        assert "uxmal" in contents              # turn-1 assistant answer

        # Episodic durability: a *fresh* EpisodicMemory over the same on-disk log
        # replays the whole thread (cold-process reconstruction).
        cold = EpisodicMemory(env.log)
        events = await cold.replay(session_id=sid)
        types = [e.event_type.value for e in events]
        assert types.count("user_message") >= 2
        assert types.count("final_answer") >= 2

        # And the log really hit disk.
        log_files = list((env.log._root).rglob("*"))
        assert any(f.is_file() for f in log_files), "episodic log was not persisted to disk"


# ---------------------------------------------------------------------------
# Long-term: promote / recall / injection, and real-LLM reconcile + distill.
# ---------------------------------------------------------------------------


class TestLongTermLive:
    async def test_promote_recall_and_memory_block_injection(self, env):
        lt = env.long_term
        await lt.setup()
        # A preference auto-promotes to active (the gate for low-risk signals).
        await lt.promote(
            candidate=MemoryCandidate(
                content=(
                    "The user is studying Maya archaeology and prefers concise "
                    "answers that name the archaeological site first."
                ),
                kind=MemoryKind.PREFERENCE,
                entities=["maya archaeology"],
                confidence=0.7,
            )
        )

        recalled = await lt.recall(query="how should answers about Maya sites be formatted?")
        assert any("concise" in r.content.lower() for r in recalled), (
            f"expected the preference to be recalled; got {[r.content for r in recalled]}"
        )

        # Wired into the runner, recall injects a memory-derived system block.
        runner = env.runner(with_long_term=True)
        captured: list = []
        orig = _llm.complete_stream

        def _spy(messages, *a, **kw):
            captured.append(messages)
            return orig(messages, *a, **kw)

        _llm.complete_stream = _spy
        try:
            await _query(runner, "How do I like my answers about Maya sites?")
        finally:
            _llm.complete_stream = orig

        system_blocks = [
            m["content"] for msgs in captured for m in msgs if m.get("role") == "system"
        ]
        assert any("memory-derived" in b and "concise" in b for b in system_blocks), (
            "expected a memory-derived system block carrying the preference"
        )

    async def test_reconcile_duplicate_with_real_llm(self, env):
        # A fresh long-term store so this test's reconciliation is isolated.
        persist = Path(env.log._root).parent / "reconcile"
        lt = LongTermMemory(
            SQLiteStructuredStore(persist / "lt.sqlite").with_scope(AppScope(app_id="recon")),
            FAISSVectorStore(path=persist / "lt_faiss").with_scope(AppScope(app_id="recon")),
            _llm,
            _embedder,
            app_id="recon",
        )
        await lt.setup()

        first = await lt.promote(
            candidate=MemoryCandidate(
                content="The user is researching the ancient Maya civilization.",
                kind=MemoryKind.PREFERENCE,
                entities=["maya"],
                confidence=0.7,
            )
        )
        # A paraphrase of the same claim — the real LLM should UPDATE/NOOP, not
        # add a contradiction, so the store stays curated (no duplicate ADD that
        # supersedes the first).
        affected = await lt.reconcile(
            candidate=MemoryCandidate(
                content="The user studies the ancient Maya people and their history.",
                kind=MemoryKind.PREFERENCE,
                entities=["maya"],
                confidence=0.7,
            )
        )
        assert affected, "reconcile returned no affected id"

        active = await lt._structured.query(  # noqa: SLF001 — verifying store contents
            lt._structured_collection, [Col("status") == MemoryStatus.ACTIVE.value]
        )
        assert len(active) >= 1
        # The original belief survives (reinforced or kept), not superseded away.
        assert any(r["memory_id"] == first for r in active) or affected == first, (
            "the duplicate observation should not have superseded the original belief"
        )

    async def test_distill_session_into_long_term_with_real_llm(self, env):
        # A short session that states a durable preference worth distilling.
        episodic = EpisodicMemory(env.log)
        short_term = ShortTermMemory(episodic=episodic, llm=_llm)
        long_term = LongTermMemory(
            SQLiteStructuredStore(Path(env.log._root).parent / "distill_lt.sqlite").with_scope(
                AppScope(app_id="distill")
            ),
            FAISSVectorStore(path=Path(env.log._root).parent / "distill_lt_faiss").with_scope(
                AppScope(app_id="distill")
            ),
            _llm,
            _embedder,
            app_id="distill",
        )
        await long_term.setup()

        sid = await short_term.start_session(app_id="distill")
        runner = QueryRunner(
            app_id="distill",
            llm=_llm,
            resources=RetrievalResources(
                document_store=env.docs,
                vector_store=env.vector,
                embedder=_embedder,
                vector_schemas=[env.vector_schema],
            ),
            memory=MemoryTiers(short_term=short_term, episodic=episodic),
        )
        await _query(
            runner,
            "Remember that I'm writing a thesis on Maya archaeology and I always "
            "want concise answers with the site name first. Which site has Maya "
            "inscriptions?",
            session_id=sid,
        )

        distiller = Distiller(episodic, long_term, _llm)
        memory_ids = await distiller.distill_session(session_id=sid)
        assert isinstance(memory_ids, list)

        # The distiller ran against the real log; whatever it promoted is in the
        # store. A preference about the thesis should be recoverable.
        all_rows = await long_term._structured.query(  # noqa: SLF001
            long_term._structured_collection
        )
        logger.info("[novel] distilled %d candidates, store has %d rows",
                    len(memory_ids), len(all_rows))
        assert all_rows, (
            "expected the distiller to extract at least one durable memory from a "
            "session that explicitly stated a stable preference"
        )


# ---------------------------------------------------------------------------
# Memory ↔ document conflict: which source wins, and is the conflict surfaced?
#
# The recalled-memory block carries an evidence-precedence policy (see
# query_runner._MEMORY_EVIDENCE_POLICY): a recalled memory is dated,
# user-attributed background, so on a conflict with what the documents currently
# say the model must prefer the document evidence (the fresher, authoritative
# source for subject-matter facts) and note the discrepancy — rather than
# silently echoing a stale memory.
#
# This drives that policy end-to-end against the real corpus.  The corpus says
# the site noted for its Maya inscriptions is Uxmal (the
# TestShortTermAndEpisodicLive turn-1 fact).  We seed an *active* long-term
# memory asserting a different site, then ask the question so recall injects the
# conflicting memory alongside the corpus.  The wrong site is Machu Picchu — an
# Inca site in Peru that this Yucatán-Maya novel never mentions — so the claim
# is a genuine contradiction the corpus cannot corroborate (unlike, say, Chichen
# Itza, which the corpus also credits with inscriptions).  That makes the
# discrepancy signal unambiguous: "Uxmal" in the answer can only come from the
# documents, and "Machu Picchu" can only come from the memory.  The test is
# non-vacuous: it first asserts the wrong memory actually reached the LLM
# context, then asserts the document fact still wins.
# ---------------------------------------------------------------------------


class TestMemoryDocumentConflictLive:
    async def test_document_wins_over_conflicting_memory_and_conflict_surfaced(self, env):
        questions = _load_questions()
        q = _find_question(questions, "noted for its maya inscriptions")
        assert "uxmal" in q["answer"].lower()  # the corpus / ground-truth fact

        lt = _fresh_long_term(env, "conflict")
        await lt.setup()
        # A subject-matter claim that contradicts the corpus.  Forced ACTIVE so it
        # is recallable (a FACT/CORRECTION would otherwise wait at pending_review),
        # framing it as a user-attributed belief the precedence policy must weigh.
        # Machu Picchu never appears in this corpus, so it is a clean contradiction.
        await lt.promote(
            candidate=MemoryCandidate(
                content=(
                    "The user noted that the site famous for its ancient Maya "
                    "inscriptions is Machu Picchu."
                ),
                kind=MemoryKind.CORRECTION,
                entities=["machu picchu", "maya inscriptions"],
                confidence=0.7,
            ),
            status=MemoryStatus.ACTIVE,
        )

        # Sanity: the wrong memory is recallable for this question's topic.
        recalled = await lt.recall(query=q["question"])
        assert any("machu picchu" in r.content.lower() for r in recalled), (
            f"expected the conflicting memory to be recalled; got "
            f"{[r.content for r in recalled]}"
        )

        runner = env.runner(long_term=lt)
        captured: list = []
        orig = _llm.complete_stream

        def _spy(messages, *a, **kw):
            captured.append(messages)
            return orig(messages, *a, **kw)

        _llm.complete_stream = _spy
        try:
            result = await _query_result(runner, q["question"])
        finally:
            _llm.complete_stream = orig
        answer = result.answer.lower()

        # Non-vacuity: the conflicting memory really reached the LLM context as a
        # memory-derived block (otherwise "documents win" would be trivial).
        system_blocks = [
            m["content"] for msgs in captured for m in msgs if m.get("role") == "system"
        ]
        assert any("machu picchu" in b.lower() and "memory-derived" in b for b in system_blocks), (
            "expected the conflicting memory injected as a memory-derived block"
        )
        assert any("machu picchu" in m.content.lower() for m in result.memories), (
            "the conflicting memory should be attached to the QueryResult"
        )

        # The precedence policy's deterministic guarantee: the document fact
        # (Uxmal) wins over the stale, user-attributed memory (Machu Picchu).
        assert "uxmal" in answer, (
            "the document evidence (Uxmal) should win over the conflicting "
            f"memory (Machu Picchu):\n{result.answer}"
        )
        # And the winning fact is grounded in retrieved document evidence, not the
        # memory: the QueryResult carries document references (vector_search chunks
        # and/or read_document slices), and at least one cites Uxmal.
        doc_refs = [c.text for c in result.chunks] + [s.text for s in result.document_slices]
        assert doc_refs, (
            "expected the answer to draw on document references (chunks/slices), "
            "confirming Uxmal came from the corpus rather than memory"
        )
        assert any("uxmal" in t.lower() for t in doc_refs), (
            "expected a retrieved document reference to ground the Uxmal answer"
        )
        # The memory must NOT have hijacked the answer: a conflicting memory that
        # is wrong should never be presented as the site.  (Machu Picchu is absent
        # from the corpus, so its only possible source here is the memory.)
        assert "machu picchu" not in answer or "uxmal" in answer, (
            f"the conflicting memory should not override the documents:\n{result.answer}"
        )
        # "Note the discrepancy" is the softer half of the policy and is
        # model-dependent — observed, not asserted.  Machu Picchu is absent from
        # the corpus, so if it surfaces at all it is the model flagging the
        # conflict; in practice the model often just drops an obviously-wrong
        # memory rather than naming it.
        surfaced = "machu picchu" in answer
        logger.info(
            "[conflict] documents won (Uxmal present); discrepancy surfaced=%s\n%s",
            surfaced, result.answer,
        )
        if not surfaced:
            logger.warning(
                "[conflict] model preferred the document but did not name the "
                "contradicted memory (discrepancy not surfaced)"
            )


# ---------------------------------------------------------------------------
# Long-term memory ↔ answer correctness: does distilled memory move the score?
#
# Measures how much long-term memory helps end-to-end answer accuracy on the
# real benchmark questions, judged by an LLM grader (mirrors
# benchmarks/graphrag/llm_evaluation/llm_answer_accuracy.py).
#
# The distiller only promotes a subject-matter fact when the USER is its source
# (an assertion, correction, or confirmation) — not when the assistant merely
# retrieved and restated it from the corpus, which the source documents already
# own (see cogbase/memory/distill.py).  This harness exercises that rule from
# both sides:
#
#   baseline   — runner with no long-term tier (corpus retrieval only).
#   control    — seed the *assistant's own* retrieved answers as ASSISTANT turns
#                and distil.  Provenance-negative: the rule should decline these,
#                so almost no durable fact is promoted.  Distilled, not re-asked.
#   treatment  — seed the *ground-truth* facts as USER assertions ("remember
#                this …") and distil.  Provenance-positive: the rule should
#                promote these user-sourced facts; accept them at the review gate
#                and re-ask, so recall can lift the score.
#
# Note on the review gate: in production only PREFERENCE / RETRIEVAL_HINT
# auto-promote to ``active``; FACT / CORRECTION wait at ``pending_review`` and
# are *not* recalled.  A distilled subject-matter fact is almost always a FACT,
# so the treatment drives the real review gate — the same ``list_pending`` /
# ``review_many`` APIs the REST endpoints (``list_pending_memories`` /
# ``review_memories``) expose — to accept the gated facts after distillation,
# measuring the lift once a reviewer has approved them, not advocating that
# production auto-activate them.
# ---------------------------------------------------------------------------

# Slice: first N questions of each type, in file order.  "Creative Generation"
# is dropped (a single question — no meaningful per-type average).
_N_PER_TYPE = 5
_SKIP_TYPES = frozenset({"Creative Generation", "Fact Retrieval"})
# Cap on questions answered+graded concurrently per run, to bound load on the
# real LLM/embedder without serializing the whole slice.
_EVAL_CONCURRENCY = 5

# Answer-correctness scoring follows the GraphRAG-Benchmark
# (``ref_projects/GraphRAG-Benchmark/Evaluation/metrics/answer_accuracy.py``):
# decompose answer + ground truth into atomic statements, classify them
# TP/FP/FN for an F-beta *factuality* score, and blend with a deterministic
# embedding cosine *similarity*.  This is far more stable run-to-run than a
# single holistic 0-1 grade, and matches the metric the README leaderboard
# numbers are scored against.
_CORRECTNESS_WEIGHTS = (0.75, 0.25)  # (factuality, semantic similarity)
_CORRECTNESS_BETA = 1.0

_STATEMENT_GENERATOR_PROMPT = """\
Given a question and an answer, analyze the complexity of each sentence in the answer. Break down each sentence into one or more fully understandable statements. Ensure that no pronouns are used in any statement. Format the outputs in JSON.

Example Input:
Question: Who was Albert Einstein and what is he best known for?
Answer: He was a German-born theoretical physicist, widely acknowledged to be one of the greatest and most influential physicists of all time. He was best known for developing the theory of relativity, he also made important contributions to the development of the theory of quantum mechanics.

Example Output:
["Albert Einstein was a German-born theoretical physicist.", "Albert Einstein is recognized as one of the greatest and most influential physicists of all time.", "Albert Einstein was best known for developing the theory of relativity.", "Albert Einstein also made important contributions to the development of the theory of quantum mechanics."]

Input Text:
Question: {question}
Answer: {answer}

Respond with a JSON array of statement strings only, no extra text or markdown fences.
Generated Statements:
"""

_CORRECTNESS_PROMPT_TEMPLATE = """\
Given a ground truth and an answer statements, analyze each statement and classify them in one of the following categories: TP (true positive): statements that are present in answer that are also directly supported by the one or more statements in ground truth, FP (false positive): statements present in the answer but not directly supported by any statement in ground truth, FN (false negative): statements found in the ground truth but not present in answer. Each statement can only belong to one of the categories. Provide a reason for each classification.

Examples:
{examples}

Current Analysis:
Question: {question}
Answer Statements: {answer}
Ground Truth Statements: {ground_truth}

Respond with JSON only, no extra text or markdown fences, of the form:
{{"TP": [{{"statement": "...", "reason": "..."}}], "FP": [...], "FN": [...]}}
"""

_CORRECTNESS_EXAMPLES = [
    {
        "input": {
            "question": "What powers the sun and what is its primary function?",
            "answer": [
                "The sun is powered by nuclear fission, similar to nuclear reactors on Earth.",
                "The primary function of the sun is to provide light to the solar system.",
            ],
            "ground_truth": [
                "The sun is powered by nuclear fusion, where hydrogen atoms fuse to form helium.",
                "This fusion process in the sun's core releases a tremendous amount of energy.",
                "The energy from the sun provides heat and light, which are essential for life on Earth.",
            ],
        },
        "output": {
            "TP": [
                {
                    "statement": "The primary function of the sun is to provide light to the solar system.",
                    "reason": "This statement is somewhat supported by the ground truth mentioning the sun providing light.",
                }
            ],
            "FP": [
                {
                    "statement": "The sun is powered by nuclear fission, similar to nuclear reactors on Earth.",
                    "reason": "This contradicts the ground truth which states the sun is powered by nuclear fusion.",
                }
            ],
            "FN": [
                {
                    "statement": "The sun is powered by nuclear fusion, where hydrogen atoms fuse to form helium.",
                    "reason": "This accurate description of the sun's power source is not included in the answer.",
                },
                {
                    "statement": "This fusion process in the sun's core releases a tremendous amount of energy.",
                    "reason": "This process and its significance are not mentioned in the answer.",
                },
                {
                    "statement": "The energy from the sun provides heat and light, which are essential for life on Earth.",
                    "reason": "The answer only mentions light, omitting heat and its necessity for life.",
                },
            ],
        },
    },
    {
        "input": {
            "question": "What is the boiling point of water?",
            "answer": ["The boiling point of water is 100 degrees Celsius at sea level"],
            "ground_truth": [
                "The boiling point of water is 100 degrees Celsius (212 degrees Fahrenheit) at sea level.",
                "The boiling point of water can change with altitude.",
            ],
        },
        "output": {
            "TP": [
                {
                    "statement": "The boiling point of water is 100 degrees Celsius at sea level",
                    "reason": "Directly supported by the ground truth which specifies 100 degrees Celsius at sea level.",
                }
            ],
            "FP": [],
            "FN": [
                {
                    "statement": "The boiling point of water can change with altitude.",
                    "reason": "This information about variation with altitude is not mentioned in the answer.",
                }
            ],
        },
    },
]


def _select_questions(questions: list[dict], n_per_type: int = _N_PER_TYPE) -> list[dict]:
    """First ``_N_PER_TYPE`` questions per type (file order), skipping skip-types."""
    by_type: dict[str, list[dict]] = {}
    selected: list[dict] = []
    for q in questions:
        qt = q.get("question_type", "Unknown")
        if qt in _SKIP_TYPES:
            continue
        bucket = by_type.setdefault(qt, [])
        if len(bucket) < n_per_type:
            bucket.append(q)
            selected.append(q)
    return selected


def _loads_lenient(content: str):
    """Parse the first JSON value in *content*, tolerating fences / trailing prose."""
    text = (content or "").strip()
    if text.startswith("```"):
        text = text.strip("`")
    start = min((i for i in (text.find("{"), text.find("[")) if i != -1), default=-1)
    if start == -1:
        raise json.JSONDecodeError("no JSON value found", text, 0)
    obj, _ = json.JSONDecoder().raw_decode(text[start:])
    return obj


def _fbeta_score(tp: int, fp: int, fn: int, beta: float = 1.0) -> float:
    """F-beta over statement classification counts (matches the benchmark)."""
    precision = tp / (tp + fp + 1e-10)
    recall = tp / (tp + fn + 1e-10)
    return (1 + beta**2) * (precision * recall) / ((beta**2 * precision) + recall + 1e-10)


async def _generate_statements(question: str, text: str) -> list[str]:
    """Decompose *text* into atomic, pronoun-free factual statements."""
    prompt = _STATEMENT_GENERATOR_PROMPT.format(question=question, answer=text)
    result = await _llm.complete([{"role": "user", "content": prompt}], model="mini")
    try:
        parsed = _loads_lenient(result.get("content") or "")
    except (json.JSONDecodeError, TypeError, ValueError):
        return [text] if text.strip() else []
    if isinstance(parsed, list):
        return [str(x) for x in parsed]
    if isinstance(parsed, dict):
        for key in ("statements", "answers", "items", "list", "output", "result"):
            value = parsed.get(key)
            if isinstance(value, list):
                return [str(x) for x in value]
        return [str(v) for v in parsed.values()]
    return [str(parsed)]


async def _calculate_factuality(
    question: str, answer_stmts: list[str], gt_stmts: list[str], beta: float
) -> tuple[float, tuple[int, int, int]]:
    """Classify answer/ground-truth statements into TP/FP/FN → F-beta score."""
    if not answer_stmts and not gt_stmts:
        return 1.0, (0, 0, 0)
    examples = "\n".join(
        f"Input: {json.dumps(ex['input'])}\nOutput: {json.dumps(ex['output'])}"
        for ex in _CORRECTNESS_EXAMPLES
    )
    prompt = _CORRECTNESS_PROMPT_TEMPLATE.format(
        examples=examples,
        question=question,
        answer=json.dumps(answer_stmts),
        ground_truth=json.dumps(gt_stmts),
    )
    result = await _llm.complete([{"role": "user", "content": prompt}], model="mini")
    try:
        parsed = _loads_lenient(result.get("content") or "")
        tp = len(parsed.get("TP", []))
        fp = len(parsed.get("FP", []))
        fn = len(parsed.get("FN", []))
    except (json.JSONDecodeError, TypeError, ValueError, AttributeError):
        return 0.0, (0, 0, 0)
    return _fbeta_score(tp, fp, fn, beta), (tp, fp, fn)


async def _semantic_similarity(answer: str, ground_truth: str) -> float:
    """Cosine similarity of the two embeddings, scaled to [0, 1] (deterministic)."""
    a_embed, gt_embed = await _embedder.embed([answer, ground_truth])
    dot = sum(x * y for x, y in zip(a_embed, gt_embed))
    na = math.sqrt(sum(x * x for x in a_embed))
    nb = math.sqrt(sum(y * y for y in gt_embed))
    if na == 0 or nb == 0:
        return 0.0
    return (dot / (na * nb) + 1) / 2


async def _judge_answer(question: str, ground_truth: str, generated: str) -> tuple[float, str]:
    """Score *generated* against *ground_truth* with the GraphRAG-Benchmark metric:
    weighted blend of statement-level F-beta factuality and embedding similarity.
    """
    w_fact, w_sim = _CORRECTNESS_WEIGHTS
    answer_stmts, gt_stmts = await asyncio.gather(
        _generate_statements(question, generated),
        _generate_statements(question, ground_truth),
    )
    factuality, (tp, fp, fn) = (
        await _calculate_factuality(question, answer_stmts, gt_stmts, _CORRECTNESS_BETA)
        if w_fact != 0 else (0.0, (0, 0, 0))
    )
    similarity = await _semantic_similarity(generated, ground_truth) if w_sim != 0 else 0.0
    score = w_fact * factuality + w_sim * similarity
    explanation = (
        f"TP={tp} FP={fp} FN={fn} factuality={factuality:.3f} "
        f"similarity={similarity:.3f} (w={w_fact:.2f}/{w_sim:.2f})"
    )
    return max(0.0, min(1.0, score)), explanation


async def _run_and_score(runner: QueryRunner, questions: list[dict], *, label: str) -> list[dict]:
    """Answer each question through *runner*, grade it, and log per-question detail.

    Questions are answered+graded concurrently (bounded by ``_EVAL_CONCURRENCY``);
    the returned rows preserve input order. Rows use the same field names as the
    GraphRAG eval harness so the written artifacts are consumable by
    ``llm_answer_accuracy.py stats``.
    """
    sem = asyncio.Semaphore(_EVAL_CONCURRENCY)
    total = len(questions)

    async def _one(i: int, q: dict) -> dict:
        async with sem:
            result = await _query_result(runner, q["question"])
            answer = result.answer
            score, explanation = await _judge_answer(q["question"], q["answer"], answer)
        row = {
            "id": q["id"],
            "question_type": q.get("question_type", "Unknown"),
            "question": q["question"],
            "ground_truth": q["answer"],
            "generated_answer": answer,
            "llm_score": score,
            "llm_explanation": explanation,
            # Every reference the answer drew on (QueryResult fields).
            "num_structured_records": len(result.structured_records),
            "structured_records": result.structured_records,
            "num_chunks": len(result.chunks),
            "chunks": [c.text for c in result.chunks],
            "num_document_slices": len(result.document_slices),
            "document_slices": [s.text for s in result.document_slices],
            "num_memory_refs": len(result.memories),
            "memory_refs": [m.content for m in result.memories],
            # Token accounting across all LLM calls for this query.
            "input_tokens": result.input_tokens,
            "output_tokens": result.output_tokens,
        }
        logger.info(
            "[answer-eval:%s] %d/%d type=%s score=%.2f "
            "refs(struct=%d chunks=%d slices=%d mem=%d) tokens(in=%d out=%d)"
            "\n  Q: %s\n  GT: %s\n  A: %s\n  why: %s",
            label, i, total, q.get("question_type"), score,
            len(result.structured_records), len(result.chunks),
            len(result.document_slices), len(result.memories),
            result.input_tokens, result.output_tokens,
            q["question"], q["answer"], answer, explanation,
        )
        return row

    return await asyncio.gather(*(_one(i, q) for i, q in enumerate(questions, 1)))


def _avg_by_type(rows: list[dict]) -> dict[str, float]:
    by_type: dict[str, list[float]] = {}
    for r in rows:
        by_type.setdefault(r["question_type"], []).append(r["llm_score"])
    return {qt: sum(v) / len(v) for qt, v in by_type.items()}


def _overall(rows: list[dict]) -> float:
    return sum(r["llm_score"] for r in rows) / len(rows) if rows else 0.0


def _format_stats(label: str, rows: list[dict]) -> str:
    """Render the per-type + overall averages for *rows* as a text block."""
    avgs = _avg_by_type(rows)
    lines = [f"{label}:"]
    for qt in sorted(avgs):
        n = sum(1 for r in rows if r["question_type"] == qt)
        lines.append(f"    {qt:<22} avg={avgs[qt]:.4f}  n={n}")
    lines.append(f"    {'OVERALL':<22} avg={_overall(rows):.4f}  n={len(rows)}")
    return "\n".join(lines)


def _format_reference_stats(label: str, rows: list[dict]) -> str:
    """Render how often answers cited each kind of reference, plus token usage.

    Covers every reference QueryResult carries — structured_records, chunks,
    document_slices, and memories. Per-type and overall: for each kind the share
    of queries that drew on at least one such reference and the average count per
    query, followed by the average input/output tokens per query.
    """
    # The reference kinds and the per-row count field each maps to.
    _KINDS = [
        ("structured", "num_structured_records"),
        ("chunks", "num_chunks"),
        ("slices", "num_document_slices"),
        ("memory", "num_memory_refs"),
    ]

    by_type: dict[str, list[dict]] = {}
    for r in rows:
        by_type.setdefault(r["question_type"], []).append(r)

    def _line(name: str, group: list[dict]) -> str:
        n = len(group)
        parts = [f"    {name:<22} n={n}"]
        for kind, field in _KINDS:
            counts = [r.get(field, 0) for r in group]
            with_refs = sum(1 for c in counts if c > 0)
            avg = sum(counts) / n if n else 0.0
            parts.append(f"{kind}={with_refs}/{n}(avg={avg:.2f})")
        avg_in = sum(r.get("input_tokens", 0) for r in group) / n if n else 0.0
        avg_out = sum(r.get("output_tokens", 0) for r in group) / n if n else 0.0
        parts.append(f"tokens(in={avg_in:.0f} out={avg_out:.0f})")
        return "  ".join(parts)

    lines = [f"{label} — query references & token usage:"]
    for qt in sorted(by_type):
        lines.append(_line(qt, by_type[qt]))
    lines.append(_line("OVERALL", rows))
    return "\n".join(lines)


def _log_stats(label: str, rows: list[dict]) -> dict[str, float]:
    block = _format_stats(f"[answer-eval] {label}", rows)
    logger.info(block)
    return _avg_by_type(rows)


async def _memory_records(lt: LongTermMemory) -> list[dict]:
    """All stored long-term records (any status), for dumping into the report."""
    return await lt._structured.query(lt._structured_collection)  # noqa: SLF001


def _format_memories(label: str, records: list[dict]) -> str:
    """Render *records* as a readable block keyed by status/kind/content."""
    lines = [f"{label} — {len(records)} memory record(s):"]
    for r in records:
        lines.append(
            f"    [{r.get('status')}] {r.get('kind')}: {r.get('content')}"
        )
    return "\n".join(lines)


def _fresh_long_term(env: _NovelEnv, name: str) -> LongTermMemory:
    """A throwaway app-scoped long-term store rooted next to the episodic log."""
    base = Path(env.log._root).parent
    return LongTermMemory(
        SQLiteStructuredStore(base / f"{name}_lt.sqlite").with_scope(AppScope(app_id=name)),
        FAISSVectorStore(path=base / f"{name}_lt_faiss").with_scope(AppScope(app_id=name)),
        _llm,
        _embedder,
        app_id=name,
    )


# A distilled subject-matter belief is durable when it lands as a FACT or a
# CORRECTION (PREFERENCE / RETRIEVAL_HINT are interaction memory, not the
# subject-matter knowledge this measurement is about).
_DURABLE_FACT_KINDS = frozenset({MemoryKind.FACT.value, MemoryKind.CORRECTION.value})

# Experiment: an application-specific topic scope handed to the distiller's
# extraction prompt (Distiller(domain_fact_guidance=...)).  It narrows which
# subject-matter facts of *this* corpus — Le Plongeon's "Vestiges of the Mayas"
# — count as durable, without touching the provenance rule.  Set to ``None`` to
# A/B against the generic prompt.
_DOMAIN_FACT_GUIDANCE = (
    "This application answers questions about Augustus Le Plongeon's scholarly "
    "work 'Vestiges of the Mayas', concerning the ancient Maya civilization of "
    "Yucatan. Durable subject-matter facts are concrete, reusable claims the "
    "work makes that a future question could turn on:\n"
    "- geography and places (e.g. Yucatan, Uxmal, Chichen-Itza, Tierra de "
    "Guerra, Mayab) and what is located at, found in, or significant about "
    "them;\n"
    "- named peoples and persons (e.g. the Mayas, Carians, Egyptians, Augustus "
    "and Mrs. Le Plongeon, Chaacmol) and their roles, customs, or "
    "contributions;\n"
    "- asserted connections or similarities BETWEEN civilizations (shared "
    "customs, religious symbols, architecture, language) — bind the specific "
    "shared trait to the specific peoples it links;\n"
    "- archaeological evidence and the specific monument, inscription, or "
    "artifact it rests on.\n"
    "Prefer facts that bind a specific named entity to a specific attribute, "
    "location, or relationship. Do not distill vague thematic impressions or "
    "whole-passage summaries."
)


def _user_fact(q: dict) -> str:
    """Phrase a benchmark Q&A as a fact the USER asserts and asks to remember.

    Routes the ground-truth fact through the user channel — the provenance the
    distiller treats as durable — instead of an assistant answer the model
    retrieved from the corpus (which the provenance rule declines).
    """
    return (
        "Please remember this for future questions. "
        f'Regarding "{q["question"]}", the established fact is: {q["answer"]}'
    )


async def _new_session(
    env: _NovelEnv, name: str
) -> tuple[LongTermMemory, EpisodicMemory, str]:
    """A fresh app-scoped long-term store + an episodic session bound to it."""
    lt = _fresh_long_term(env, name)
    await lt.setup()
    episodic = EpisodicMemory(env.log)
    short_term = ShortTermMemory(episodic=episodic, llm=_llm)
    sid = await short_term.start_session(app_id=name)
    episodic.bind_app(sid, app_id=name)
    return lt, episodic, sid


async def _distill_accept_and_collect(
    lt: LongTermMemory, episodic: EpisodicMemory, sid: str, name: str
) -> list[dict]:
    """Distil the session, accept any pending facts, return the durable records.

    FACT/CORRECTION distilled here land at ``pending_review`` and are never
    recalled until a reviewer accepts them — the same gate the API exposes via
    ``list_pending_memories`` / ``review_memories``.  Drive that gate with the
    low-level review APIs so accepted facts become recallable, rather than
    monkeypatching the auto-activate set.  Returns the active durable-kind
    records (the provenance rule's observable output).
    """
    distiller = Distiller(episodic, lt, _llm, domain_fact_guidance=_DOMAIN_FACT_GUIDANCE)
    memory_ids = await distiller.distill_session(session_id=sid)
    pending = await lt.list_pending(limit=MAX_REVIEW_BATCH)
    if pending:
        await lt.review_many(
            decisions=[ReviewDecision(memory_id=r.memory_id, accept=True) for r in pending]
        )
    active = await lt._structured.query(  # noqa: SLF001 — verifying store contents
        lt._structured_collection, [Col("status") == MemoryStatus.ACTIVE.value]
    )
    durable = [r for r in active if r.get("kind") in _DURABLE_FACT_KINDS]
    logger.info(
        "[answer-eval] %s: distilled %d candidate(s), accepted %d pending, "
        "%d active record(s) (%d durable fact)",
        name, len(memory_ids), len(pending), len(active), len(durable),
    )
    return durable


async def _seed_user_facts_and_distill(
    env: _NovelEnv, name: str, statements: list[str]
) -> tuple[LongTermMemory, list[dict]]:
    """Provenance-positive: the USER asserts each fact; distil + accept it."""
    lt, episodic, sid = await _new_session(env, name)
    for statement in statements:
        await episodic.record_user_message(session_id=sid, content=statement)
    await episodic.flush(sid)
    return lt, await _distill_accept_and_collect(lt, episodic, sid, name)


async def _seed_assistant_answers_and_distill(
    env: _NovelEnv, name: str, qa_pairs: list[tuple[str, str]]
) -> tuple[LongTermMemory, list[dict]]:
    """Provenance-negative: the assistant *answers* each question (retrieved from
    the corpus); the distiller should decline these as durable facts."""
    lt, episodic, sid = await _new_session(env, name)
    for question, answer in qa_pairs:
        await episodic.record_user_message(session_id=sid, content=question)
        await episodic.record_final_answer(session_id=sid, answer=answer)
    await episodic.flush(sid)
    return lt, await _distill_accept_and_collect(lt, episodic, sid, name)


class TestLongTermAnswerImprovementLive:
    async def test_distill_correct_answer(self, env):
        questions = _load_questions()
        selected = _select_questions(questions)
        logger.info(
            "[distill-eval] %d questions across types: %s",
            len(selected), sorted(set(q["question_type"] for q in selected)),
        )

        treatment_lt, treatment_facts = await _seed_assistant_answers_and_distill(
            env, "treatment", [(q["question"], q["answer"]) for q in selected]
        )
        logger.info(_format_memories(
            "treatment memory (user-asserted)", await _memory_records(treatment_lt)
        ))


    async def test_long_term_memory_improves_answer_correctness(self, env):
        questions = _load_questions()
        selected = _select_questions(questions)
        logger.info(
            "[answer-eval] %d questions across types: %s",
            len(selected), sorted(set(q["question_type"] for q in selected)),
        )
        artifacts = Path(env.log._root).parent / "answer_eval"
        artifacts.mkdir(parents=True, exist_ok=True)
        report = artifacts / "stats.txt"

        def _write(name: str, rows: list[dict]) -> None:
            (artifacts / f"{name}.json").write_text(
                json.dumps(rows, indent=2, ensure_ascii=False), encoding="utf-8"
            )

        def _append(block: str) -> None:
            with report.open("a", encoding="utf-8") as fh:
                fh.write(block + "\n\n")

        # --- Baseline: no long-term tier ----------------------------------
        baseline = await _run_and_score(env.runner(), selected, label="baseline")
        _write("baseline", baseline)
        _log_stats("baseline (no long-term)", baseline)
        _append(_format_stats("baseline (no long-term)", baseline))
        _append(_format_reference_stats("baseline (no long-term)", baseline))

        # --- Control (provenance-negative) --------------------------------
        # The assistant's own retrieved answers, recorded as ASSISTANT turns.
        # The distiller's provenance rule should decline corpus-retrieved
        # assistant facts, so almost nothing durable is promoted.  Distilled
        # only; not re-asked (its purpose is the fact-count comparison below).
        control_lt, control_facts = await _seed_assistant_answers_and_distill(
            env, "control", [(r["question"], r["generated_answer"]) for r in baseline]
        )
        _append(_format_memories(
            "control memory (assistant-retrieved)", await _memory_records(control_lt)
        ))

        # --- Treatment (provenance-positive) ------------------------------
        # The ground-truth facts, recorded as USER assertions.  These are
        # user-sourced subject-matter facts the rule should promote; accept them
        # at the review gate and re-ask so recall can lift the score.
        treatment_lt, treatment_facts = await _seed_user_facts_and_distill(
            env, "treatment", [_user_fact(q) for q in selected]
        )
        # simply distill the test answer extracts few memory records (0 or 1 for mini model)
        #treatment_lt, treatment_facts = await _seed_assistant_answers_and_distill(
        #    env, "treatment", [(q["question"], q["answer"]) for q in selected]
        #)
        treatment = await _run_and_score(
            env.runner(long_term=treatment_lt), selected, label="treatment"
        )
        _write("treatment", treatment)
        _log_stats("treatment (user-asserted facts)", treatment)
        _append(_format_stats("treatment (user-asserted facts)", treatment))
        _append(_format_reference_stats("treatment (user-asserted facts)", treatment))
        _append(_format_memories(
            "treatment memory (user-asserted)", await _memory_records(treatment_lt)
        ))

        # --- Comparison ----------------------------------------------------
        base_overall, treatment_overall = _overall(baseline), _overall(treatment)
        logger.info(
            "[answer-eval] OVERALL  baseline=%.4f  treatment=%.4f  "
            "durable facts: control=%d treatment=%d  (artifacts: %s)",
            base_overall, treatment_overall,
            len(control_facts), len(treatment_facts), artifacts,
        )

        # Final consolidated stats: per-type/overall scores and reference+token
        # usage for both scored runs side by side in one log block.
        summary = "\n\n".join(
            block
            for label, rows in (
                ("baseline (no long-term)", baseline),
                ("treatment (user-asserted facts)", treatment),
            )
            for block in (_format_stats(label, rows), _format_reference_stats(label, rows))
        )
        logger.info("[answer-eval] final stats\n%s", summary)

        # Sanity: both scored runs cover the full slice.
        assert len(baseline) == len(treatment) == len(selected)
        # Provenance rule: a fact the USER asserts distils into durable memory;
        # the same fact merely retrieved and restated by the assistant does not.
        assert len(treatment_facts) > len(control_facts), (
            "user-asserted facts should distil into more durable memory than "
            f"assistant-retrieved answers: treatment={len(treatment_facts)} "
            f"control={len(control_facts)}"
        )
        # Measurement: user-supplied ground-truth memory should not lower, and
        # should lift, accuracy vs. the no-memory baseline.
        assert treatment_overall >= base_overall, (
            "user-asserted long-term memory should not lower accuracy: "
            f"baseline={base_overall:.4f} treatment={treatment_overall:.4f}"
        )

    async def test_answer_scores_are_stable_across_runs(self, env):
        """Run the same question slice twice through an unchanged baseline runner
        and log the scores, to gauge how stable the LLM grades are run-to-run.

        Diagnostic only: the runner and judge are both non-deterministic, so this
        records the per-question and overall drift (and writes the two runs as
        artifacts) rather than asserting a tight bound — it only guards against a
        wildly unstable harness.
        """
        questions = _load_questions()
        selected = _select_questions(questions)
        logger.info(
            "[stability] %d questions across types: %s",
            len(selected), sorted(set(q["question_type"] for q in selected)),
        )
        artifacts = Path(env.log._root).parent / "answer_eval"
        artifacts.mkdir(parents=True, exist_ok=True)
        report = artifacts / "stability.txt"

        def _write(name: str, rows: list[dict]) -> None:
            (artifacts / f"{name}.json").write_text(
                json.dumps(rows, indent=2, ensure_ascii=False), encoding="utf-8"
            )

        def _append(block: str) -> None:
            with report.open("a", encoding="utf-8") as fh:
                fh.write(block + "\n\n")

        # Two independent passes over the same slice with the same (no long-term)
        # runner config; only sampling noise should differ between them.
        run1 = await _run_and_score(env.runner(), selected, label="stability-run1")
        run2 = await _run_and_score(env.runner(), selected, label="stability-run2")
        _write("stability_run1", run1)
        _write("stability_run2", run2)

        for label, rows in (("run1", run1), ("run2", run2)):
            _log_stats(f"stability {label}", rows)
            _append(_format_stats(f"stability {label}", rows))

        # Per-question drift, keyed by id so the two ordered runs line up.
        by_id2 = {r["id"]: r for r in run2}
        diffs = [
            (r1["id"], r1["question_type"], r1["llm_score"],
             by_id2[r1["id"]]["llm_score"])
            for r1 in run1 if r1["id"] in by_id2
        ]
        abs_diffs = [abs(s1 - s2) for _, _, s1, s2 in diffs]
        mean_abs = sum(abs_diffs) / len(abs_diffs) if abs_diffs else 0.0
        max_abs = max(abs_diffs) if abs_diffs else 0.0
        flipped = sum(1 for d in abs_diffs if d > 0.0)
        overall1, overall2 = _overall(run1), _overall(run2)

        detail = ["stability per-question score drift (run1 -> run2):"]
        for qid, qt, s1, s2 in diffs:
            detail.append(f"    {qid} [{qt}] {s1:.2f} -> {s2:.2f}  (|d|={abs(s1-s2):.2f})")
        detail.append(
            f"    SUMMARY overall {overall1:.4f} -> {overall2:.4f} "
            f"(|d|={abs(overall1-overall2):.4f})  "
            f"mean|d|={mean_abs:.4f} max|d|={max_abs:.4f} "
            f"changed={flipped}/{len(abs_diffs)}"
        )
        block = "\n".join(detail)
        logger.info("[stability]\n%s", block)
        _append(block)

        # Both passes must cover the full slice; guard only against a grossly
        # unstable harness (large average per-question swing).
        assert len(run1) == len(run2) == len(selected)
        assert mean_abs <= 0.5, (
            "answer scores are unexpectedly unstable across identical runs: "
            f"mean|d|={mean_abs:.4f} max|d|={max_abs:.4f} "
            f"overall {overall1:.4f} -> {overall2:.4f}"
        )


# ---------------------------------------------------------------------------
# Fixture regeneration (not a test) — kept here so the corpus/question slice is
# reproducible from the benchmark sources.
# ---------------------------------------------------------------------------


def _regen_fixtures() -> None:
    """Rebuild tests/test_data/novel_30752_{corpus.txt,questions.json} from the benchmark."""
    root = Path(__file__).resolve().parents[2] / "ref_projects" / "GraphRAG-Benchmark" / "Datasets"
    corpus = json.loads((root / "Corpus" / "novel.json").read_text())
    entry = next(c for c in corpus if c["corpus_name"] == "Novel-30752")
    _DATA_DIR.mkdir(parents=True, exist_ok=True)
    _CORPUS_FILE.write_text(entry["context"], encoding="utf-8")
    qs = json.loads((root / "Questions" / "novel_questions.json").read_text())
    matches = [q for q in qs if q.get("source") == "Novel-30752"]
    _QUESTIONS_FILE.write_text(json.dumps(matches, indent=2, ensure_ascii=False), encoding="utf-8")


if __name__ == "__main__":
    _regen_fixtures()
    print("regenerated novel-30752 fixtures")
