"""Live end-to-end memory tests over a real GraphRAG benchmark corpus.

Drives all three memory tiers — short-term (session working context), episodic
(the durable append-only log), and long-term (curated cross-session records) —
against the first novel corpus of the GraphRAG-Benchmark, ``Novel-30752``
("Vestiges of the Mayas"), and the 87 benchmark questions written for it.

The corpus text and questions are checked in as fixtures under ``tests/data/``
(regenerated by ``_regen_fixtures`` at the bottom of this file from
``ref_projects/GraphRAG-Benchmark/Datasets/``).

Nothing is faked: the LLM and embedder come from ``.env.yaml`` (see
``tests/live_setup``) and every store is a real persistent backend —
``SQLiteStructuredStore`` (a sqlite file), ``FAISSVectorStore`` (file-backed
FAISS), ``LocalFSLogStore`` and ``LocalFSDocumentStore`` (on-disk). The novel is
chunked, embedded, and upserted into FAISS so the query runner answers real
questions through ``vector_search``; the memory tiers ride on top.

Run with::

    pytest tests/memory/test_novel_memory_live.py -m live
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
from pathlib import Path

import pytest
import yaml

from cogbase.core.models import Document
from cogbase.core.query_runner import MemoryTiers, QueryResult, QueryRunner, RetrievalResources
from cogbase.memory import (
    Distiller,
    EpisodicMemory,
    LongTermMemory,
    ReviewDecision,
    ShortTermMemory,
)
from cogbase.memory.long_term import MAX_REVIEW_BATCH
from cogbase.memory.models import MemoryCandidate, MemoryKind, MemoryStatus
from cogbase.pipeline.chunking.langchain import build_recursive_chunker
from cogbase.stores.document.local_fs import LocalFSDocumentStore
from cogbase.stores.filters import Col
from cogbase.stores.log.local_fs import LocalFSLogStore
from cogbase.stores.scope import AppScope
from cogbase.stores.structured.sqlite import SQLiteStructuredStore
from cogbase.stores.vector.base import VectorCollectionSchema
from cogbase.stores.vector.faiss_store import FAISSVectorStore
from tests.live_setup import make_llm, make_embedding

logger = logging.getLogger(__name__)

_llm = make_llm()
_embedder = make_embedding()

pytest.importorskip("faiss", reason="faiss not installed")

pytestmark = [
    pytest.mark.live,
    pytest.mark.skipif(
        _llm is None or _embedder is None,
        reason="No LLM/embedder configured: set llm+embedding in .env.yaml or OPENAI_API_KEY",
    ),
]

_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
_CORPUS_FILE = _DATA_DIR / "novel_30752_corpus.txt"
_QUESTIONS_FILE = _DATA_DIR / "novel_30752_questions.json"

# Reuse the GraphRAG benchmark's query prompt so the runner answers in the same
# concise, evidence-grounded style the benchmark grades against.
_BENCH_APP_FILE = (
    Path(__file__).resolve().parents[2]
    / "benchmarks" / "graphrag" / "bench_app_simple.yaml"
)
_QUERY_PROMPT = yaml.safe_load(_BENCH_APP_FILE.read_text(encoding="utf-8"))["query_prompt"]

_APP_ID = "novel-30752"
_PASSAGES = "novel_passages"


def _load_questions() -> list[dict]:
    return json.loads(_QUESTIONS_FILE.read_text(encoding="utf-8"))


def _find_question(questions: list[dict], needle: str) -> dict:
    """Return the benchmark question whose text contains *needle* (case-insensitive)."""
    needle = needle.lower()
    for q in questions:
        if needle in q["question"].lower():
            return q
    raise AssertionError(f"no benchmark question contains {needle!r}")


class _NovelEnv:
    """Bundle of the persistent stores + memory tiers for one test session."""

    def __init__(self, *, vector, structured, log, docs, episodic, short_term,
                 long_term, vector_schema):
        self.vector = vector
        self.structured = structured
        self.log = log
        self.docs = docs
        self.episodic = episodic
        self.short_term = short_term
        self.long_term = long_term
        self.vector_schema = vector_schema

    def runner(self, *, with_long_term=False, long_term=None) -> QueryRunner:
        """Build a runner over the ingested corpus.

        ``with_long_term`` wires this env's own long-term store; ``long_term``
        overrides it with any other store (used to compare freshly-distilled
        memory stores against the no-memory baseline).
        """
        lt = long_term if long_term is not None else (self.long_term if with_long_term else None)
        return QueryRunner(
            app_id=_APP_ID,
            llm=_llm,
            resources=RetrievalResources(
                document_store=self.docs,
                vector_store=self.vector,
                embedder=_embedder,
                vector_schemas=[self.vector_schema],
            ),
            memory=MemoryTiers(
                short_term=self.short_term,
                episodic=self.episodic,
                long_term=lt,
            ),
        )


async def _build_and_ingest(persist: Path) -> _NovelEnv:
    """Build every persistent store and ingest the novel into FAISS (once)."""
    corpus = _CORPUS_FILE.read_text(encoding="utf-8")

    vector = FAISSVectorStore(path=persist / "novel_faiss")
    structured = SQLiteStructuredStore(persist / "novel.sqlite")
    log = LocalFSLogStore(persist / "logs")
    docs = LocalFSDocumentStore(persist / "docs")

    episodic = EpisodicMemory(log)
    short_term = ShortTermMemory(episodic=episodic, llm=_llm)

    # Long-term rides on its own app-scoped persistent stores (sqlite + faiss).
    long_term = LongTermMemory(
        SQLiteStructuredStore(persist / "long_term.sqlite").with_scope(AppScope(app_id=_APP_ID)),
        FAISSVectorStore(path=persist / "long_term_faiss").with_scope(AppScope(app_id=_APP_ID)),
        _llm,
        _embedder,
        app_id=_APP_ID,
    )

    # Chunk → embed → upsert the novel into a real FAISS collection.
    chunks = build_recursive_chunker(chunk_size=1024, overlap=128).chunk(
        Document(doc_id="Novel-30752", text=corpus)
    )
    embeddings = await _embedder.embed([c.text for c in chunks])
    dims = len(embeddings[0])

    vector_schema = VectorCollectionSchema(
        name=_PASSAGES,
        dimensions=dims,
        description="Passages from the novel 'Vestiges of the Mayas' (Novel-30752).",
    )
    env = _NovelEnv(
        vector=vector, structured=structured, log=log, docs=docs,
        episodic=episodic, short_term=short_term, long_term=long_term,
        vector_schema=vector_schema,
    )
    await vector.create_collection(env.vector_schema)
    await vector.upsert(
        _PASSAGES,
        [c.model_copy(update={"embedding": e}) for c, e in zip(chunks, embeddings)],
    )
    logger.info("[novel] ingested %d passages, dims=%d", len(chunks), dims)
    return env


@pytest.fixture(scope="module")
def env(tmp_path_factory) -> _NovelEnv:
    """Module-scoped: build the stores and ingest the corpus once.

    Built on a throwaway loop (the stores are loop-agnostic — sqlite is sync,
    FAISS/localfs use ``get_event_loop`` at call time), then reused by each
    function-scoped async test.
    """
    persist = tmp_path_factory.mktemp("novel_memory")
    return asyncio.run(_build_and_ingest(persist))


async def _query_result(runner: QueryRunner, text: str, *, session_id: str | None = None) -> QueryResult:
    result: QueryResult | None = None
    async for item in runner.run(text, base_prompt=_QUERY_PROMPT, session_id=session_id):
        if isinstance(item, QueryResult):
            result = item
    assert result is not None, f"runner produced no QueryResult for {text!r}"
    return result


async def _query(runner: QueryRunner, text: str, *, session_id: str | None = None) -> str:
    return (await _query_result(runner, text, session_id=session_id)).answer


# ---------------------------------------------------------------------------
# Short-term (session) + episodic, driven by real benchmark questions.
# ---------------------------------------------------------------------------


class TestShortTermAndEpisodicLive:
    async def test_multiturn_session_carries_context_and_persists_log(self, env):
        questions = _load_questions()
        # A fact-retrieval question whose answer ("Uxmal") is a distinctive token.
        q1 = _find_question(questions, "noted for its maya inscriptions")
        assert "uxmal" in q1["answer"].lower()

        sid = await env.short_term.start_session(app_id=_APP_ID)

        # Turn 1 — answered through real vector_search over the novel.
        answer1 = (await _query(env.runner(), q1["question"], session_id=sid)).lower()
        assert "uxmal" in answer1, f"expected Uxmal in turn-1 answer:\n{answer1}"

        # Turn 2 — a bare follow-up that only resolves via short-term context.
        # "that same site" refers to Uxmal from turn 1; the Dwarf's House mystery
        # is at Uxmal in the corpus. No caller history is passed: short-term must
        # rehydrate the prior turn from the episodic log.
        answer2 = (
            await _query(
                env.runner(),
                "At that same site, what legendary building is tied to mysteries there?",
                session_id=sid,
            )
        ).lower()
        assert "dwarf" in answer2, (
            "expected the Dwarf's House (Uxmal) — turn 2 needs short-term context "
            f"to resolve 'that same site':\n{answer2}"
        )

        # Short-term projection: both turns are present in the rehydrated thread.
        state = await env.short_term.get(sid)
        assert state is not None
        contents = " ".join(m.content for m in state.messages).lower()
        assert "maya inscriptions" in contents  # turn-1 user message
        assert "uxmal" in contents              # turn-1 assistant answer

        # Episodic durability: a *fresh* EpisodicMemory over the same on-disk log
        # replays the whole thread (cold-process reconstruction).
        cold = EpisodicMemory(env.log)
        events = await cold.replay(session_id=sid)
        types = [e.event_type.value for e in events]
        assert types.count("user_message") >= 2
        assert types.count("final_answer") >= 2

        # And the log really hit disk.
        log_files = list((env.log._root).rglob("*"))
        assert any(f.is_file() for f in log_files), "episodic log was not persisted to disk"


# ---------------------------------------------------------------------------
# Long-term: promote / recall / injection, and real-LLM reconcile + distill.
# ---------------------------------------------------------------------------


class TestLongTermLive:
    async def test_promote_recall_and_memory_block_injection(self, env):
        lt = env.long_term
        await lt.setup()
        # A preference auto-promotes to active (the gate for low-risk signals).
        await lt.promote(
            candidate=MemoryCandidate(
                content=(
                    "The user is studying Maya archaeology and prefers concise "
                    "answers that name the archaeological site first."
                ),
                kind=MemoryKind.PREFERENCE,
                entities=["maya archaeology"],
                confidence=0.7,
            )
        )

        recalled = await lt.recall(query="how should answers about Maya sites be formatted?")
        assert any("concise" in r.content.lower() for r in recalled), (
            f"expected the preference to be recalled; got {[r.content for r in recalled]}"
        )

        # Wired into the runner, recall injects a memory-derived system block.
        runner = env.runner(with_long_term=True)
        captured: list = []
        orig = _llm.complete_stream

        def _spy(messages, *a, **kw):
            captured.append(messages)
            return orig(messages, *a, **kw)

        _llm.complete_stream = _spy
        try:
            await _query(runner, "How do I like my answers about Maya sites?")
        finally:
            _llm.complete_stream = orig

        system_blocks = [
            m["content"] for msgs in captured for m in msgs if m.get("role") == "system"
        ]
        assert any("memory-derived" in b and "concise" in b for b in system_blocks), (
            "expected a memory-derived system block carrying the preference"
        )

    async def test_reconcile_duplicate_with_real_llm(self, env):
        # A fresh long-term store so this test's reconciliation is isolated.
        persist = Path(env.log._root).parent / "reconcile"
        lt = LongTermMemory(
            SQLiteStructuredStore(persist / "lt.sqlite").with_scope(AppScope(app_id="recon")),
            FAISSVectorStore(path=persist / "lt_faiss").with_scope(AppScope(app_id="recon")),
            _llm,
            _embedder,
            app_id="recon",
        )
        await lt.setup()

        first = await lt.promote(
            candidate=MemoryCandidate(
                content="The user is researching the ancient Maya civilization.",
                kind=MemoryKind.PREFERENCE,
                entities=["maya"],
                confidence=0.7,
            )
        )
        # A paraphrase of the same claim — the real LLM should UPDATE/NOOP, not
        # add a contradiction, so the store stays curated (no duplicate ADD that
        # supersedes the first).
        affected = await lt.reconcile(
            candidate=MemoryCandidate(
                content="The user studies the ancient Maya people and their history.",
                kind=MemoryKind.PREFERENCE,
                entities=["maya"],
                confidence=0.7,
            )
        )
        assert affected, "reconcile returned no affected id"

        active = await lt._structured.query(  # noqa: SLF001 — verifying store contents
            lt._structured_collection, [Col("status") == MemoryStatus.ACTIVE.value]
        )
        assert len(active) >= 1
        # The original belief survives (reinforced or kept), not superseded away.
        assert any(r["memory_id"] == first for r in active) or affected == first, (
            "the duplicate observation should not have superseded the original belief"
        )

    async def test_distill_session_into_long_term_with_real_llm(self, env):
        # A short session that states a durable preference worth distilling.
        episodic = EpisodicMemory(env.log)
        short_term = ShortTermMemory(episodic=episodic, llm=_llm)
        long_term = LongTermMemory(
            SQLiteStructuredStore(Path(env.log._root).parent / "distill_lt.sqlite").with_scope(
                AppScope(app_id="distill")
            ),
            FAISSVectorStore(path=Path(env.log._root).parent / "distill_lt_faiss").with_scope(
                AppScope(app_id="distill")
            ),
            _llm,
            _embedder,
            app_id="distill",
        )
        await long_term.setup()

        sid = await short_term.start_session(app_id="distill")
        runner = QueryRunner(
            app_id="distill",
            llm=_llm,
            resources=RetrievalResources(
                document_store=env.docs,
                vector_store=env.vector,
                embedder=_embedder,
                vector_schemas=[env.vector_schema],
            ),
            memory=MemoryTiers(short_term=short_term, episodic=episodic),
        )
        await _query(
            runner,
            "Remember that I'm writing a thesis on Maya archaeology and I always "
            "want concise answers with the site name first. Which site has Maya "
            "inscriptions?",
            session_id=sid,
        )

        distiller = Distiller(episodic, long_term, _llm)
        memory_ids = await distiller.distill_session(session_id=sid)
        assert isinstance(memory_ids, list)

        # The distiller ran against the real log; whatever it promoted is in the
        # store. A preference about the thesis should be recoverable.
        all_rows = await long_term._structured.query(  # noqa: SLF001
            long_term._structured_collection
        )
        logger.info("[novel] distilled %d candidates, store has %d rows",
                    len(memory_ids), len(all_rows))
        assert all_rows, (
            "expected the distiller to extract at least one durable memory from a "
            "session that explicitly stated a stable preference"
        )


# ---------------------------------------------------------------------------
# Memory ↔ document conflict: which source wins, and is the conflict surfaced?
#
# The recalled-memory block carries an evidence-precedence policy (see
# query_runner._MEMORY_EVIDENCE_POLICY): a recalled memory is dated,
# user-attributed background, so on a conflict with what the documents currently
# say the model must prefer the document evidence (the fresher, authoritative
# source for subject-matter facts) and note the discrepancy — rather than
# silently echoing a stale memory.
#
# This drives that policy end-to-end against the real corpus.  The corpus says
# the site noted for its Maya inscriptions is Uxmal (the
# TestShortTermAndEpisodicLive turn-1 fact).  We seed an *active* long-term
# memory asserting a different site, then ask the question so recall injects the
# conflicting memory alongside the corpus.  The wrong site is Machu Picchu — an
# Inca site in Peru that this Yucatán-Maya novel never mentions — so the claim
# is a genuine contradiction the corpus cannot corroborate (unlike, say, Chichen
# Itza, which the corpus also credits with inscriptions).  That makes the
# discrepancy signal unambiguous: "Uxmal" in the answer can only come from the
# documents, and "Machu Picchu" can only come from the memory.  The test is
# non-vacuous: it first asserts the wrong memory actually reached the LLM
# context, then asserts the document fact still wins.
# ---------------------------------------------------------------------------


class TestMemoryDocumentConflictLive:
    async def test_document_wins_over_conflicting_memory_and_conflict_surfaced(self, env):
        questions = _load_questions()
        q = _find_question(questions, "noted for its maya inscriptions")
        assert "uxmal" in q["answer"].lower()  # the corpus / ground-truth fact

        lt = _fresh_long_term(env, "conflict")
        await lt.setup()
        # A subject-matter claim that contradicts the corpus.  Forced ACTIVE so it
        # is recallable (a FACT/CORRECTION would otherwise wait at pending_review),
        # framing it as a user-attributed belief the precedence policy must weigh.
        # Machu Picchu never appears in this corpus, so it is a clean contradiction.
        await lt.promote(
            candidate=MemoryCandidate(
                content=(
                    "The user noted that the site famous for its ancient Maya "
                    "inscriptions is Machu Picchu."
                ),
                kind=MemoryKind.CORRECTION,
                entities=["machu picchu", "maya inscriptions"],
                confidence=0.7,
            ),
            status=MemoryStatus.ACTIVE,
        )

        # Sanity: the wrong memory is recallable for this question's topic.
        recalled = await lt.recall(query=q["question"])
        assert any("machu picchu" in r.content.lower() for r in recalled), (
            f"expected the conflicting memory to be recalled; got "
            f"{[r.content for r in recalled]}"
        )

        runner = env.runner(long_term=lt)
        captured: list = []
        orig = _llm.complete_stream

        def _spy(messages, *a, **kw):
            captured.append(messages)
            return orig(messages, *a, **kw)

        _llm.complete_stream = _spy
        try:
            result = await _query_result(runner, q["question"])
        finally:
            _llm.complete_stream = orig
        answer = result.answer.lower()

        # Non-vacuity: the conflicting memory really reached the LLM context as a
        # memory-derived block (otherwise "documents win" would be trivial).
        system_blocks = [
            m["content"] for msgs in captured for m in msgs if m.get("role") == "system"
        ]
        assert any("machu picchu" in b.lower() and "memory-derived" in b for b in system_blocks), (
            "expected the conflicting memory injected as a memory-derived block"
        )
        assert any("machu picchu" in m.content.lower() for m in result.memories), (
            "the conflicting memory should be attached to the QueryResult"
        )

        # The precedence policy's deterministic guarantee: the document fact
        # (Uxmal) wins over the stale, user-attributed memory (Machu Picchu).
        assert "uxmal" in answer, (
            "the document evidence (Uxmal) should win over the conflicting "
            f"memory (Machu Picchu):\n{result.answer}"
        )
        # And the winning fact is grounded in retrieved document evidence, not the
        # memory: the QueryResult carries document references (vector_search chunks
        # and/or read_document slices), and at least one cites Uxmal.
        doc_refs = [c.text for c in result.chunks] + [s.text for s in result.document_slices]
        assert doc_refs, (
            "expected the answer to draw on document references (chunks/slices), "
            "confirming Uxmal came from the corpus rather than memory"
        )
        assert any("uxmal" in t.lower() for t in doc_refs), (
            "expected a retrieved document reference to ground the Uxmal answer"
        )
        # The memory must NOT have hijacked the answer: a conflicting memory that
        # is wrong should never be presented as the site.  (Machu Picchu is absent
        # from the corpus, so its only possible source here is the memory.)
        assert "machu picchu" not in answer or "uxmal" in answer, (
            f"the conflicting memory should not override the documents:\n{result.answer}"
        )
        # "Note the discrepancy" is the softer half of the policy and is
        # model-dependent — observed, not asserted.  Machu Picchu is absent from
        # the corpus, so if it surfaces at all it is the model flagging the
        # conflict; in practice the model often just drops an obviously-wrong
        # memory rather than naming it.
        surfaced = "machu picchu" in answer
        logger.info(
            "[conflict] documents won (Uxmal present); discrepancy surfaced=%s\n%s",
            surfaced, result.answer,
        )
        if not surfaced:
            logger.warning(
                "[conflict] model preferred the document but did not name the "
                "contradicted memory (discrepancy not surfaced)"
            )

